//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldBusiness.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NomencladoresResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NomencladoresResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldBusiness.Domain.Resources.NomencladoresResources", typeof(NomencladoresResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceptos de Ajuste.
        /// </summary>
        public static string ConceptoAjuste {
            get {
                return ResourceManager.GetString("ConceptoAjuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        public static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogos y clasificadores del sistema ERP.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecimientos.
        /// </summary>
        public static string Establecimiento {
            get {
                return ResourceManager.GetString("Establecimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichas de Producto (BOM).
        /// </summary>
        public static string FichaProducto {
            get {
                return ResourceManager.GetString("FichaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Cuentas.
        /// </summary>
        public static string GrupoCuenta {
            get {
                return ResourceManager.GetString("GrupoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta sección agrupa todos los catálogos y clasificadores del ERP.
        /// </summary>
        public static string InfoRemarks {
            get {
                return ResourceManager.GetString("InfoRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas.
        /// </summary>
        public static string Linea {
            get {
                return ResourceManager.GetString("Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monedas.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomencladores.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubGrupos de Cuentas.
        /// </summary>
        public static string SubGrupoCuenta {
            get {
                return ResourceManager.GetString("SubGrupoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubLíneas.
        /// </summary>
        public static string SubLinea {
            get {
                return ResourceManager.GetString("SubLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        public static string Transaccion {
            get {
                return ResourceManager.GetString("Transaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de Medida.
        /// </summary>
        public static string UnidadMedida {
            get {
                return ResourceManager.GetString("UnidadMedida", resourceCulture);
            }
        }
    }
}
