//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldBusiness.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldBusiness.Domain.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta deshabilitada.
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la Cuenta.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta bloqueada.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe contener solo números (00-99).
        /// </summary>
        public static string CodigoFormato {
            get {
                return ResourceManager.GetString("CodigoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe tener exactamente {1} caracteres.
        /// </summary>
        public static string CodigoLongitud {
            get {
                return ResourceManager.GetString("CodigoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código es obligatorio.
        /// </summary>
        public static string CodigoObligatorio {
            get {
                return ResourceManager.GetString("CodigoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe ser numérico con 8 dígitos (Ejemplo: 10000010).
        /// </summary>
        public static string CuentaCodigoFormato {
            get {
                return ResourceManager.GetString("CuentaCodigoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la cuenta debe tener exactamente 8 caracteres.
        /// </summary>
        public static string CuentaCodigoLongitud {
            get {
                return ResourceManager.GetString("CuentaCodigoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede exceder {1} caracteres.
        /// </summary>
        public static string DescripcionLongitud {
            get {
                return ResourceManager.GetString("DescripcionLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción es obligatoria.
        /// </summary>
        public static string DescripcionObligatoria {
            get {
                return ResourceManager.GetString("DescripcionObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Field_Cancelado {
            get {
                return ResourceManager.GetString("Field_Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Field_Codigo {
            get {
                return ResourceManager.GetString("Field_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por.
        /// </summary>
        public static string Field_CreadoPor {
            get {
                return ResourceManager.GetString("Field_CreadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        public static string Field_Cuentas {
            get {
                return ResourceManager.GetString("Field_Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Field_Descripcion {
            get {
                return ResourceManager.GetString("Field_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deudora.
        /// </summary>
        public static string Field_Deudora {
            get {
                return ResourceManager.GetString("Field_Deudora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación.
        /// </summary>
        public static string Field_FechaCreacion {
            get {
                return ResourceManager.GetString("Field_FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de modificación.
        /// </summary>
        public static string Field_FechaModificacion {
            get {
                return ResourceManager.GetString("Field_FechaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Cuenta.
        /// </summary>
        public static string Field_GrupoCuenta {
            get {
                return ResourceManager.GetString("Field_GrupoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea.
        /// </summary>
        public static string Field_Linea {
            get {
                return ResourceManager.GetString("Field_Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado por.
        /// </summary>
        public static string Field_ModificadoPor {
            get {
                return ResourceManager.GetString("Field_ModificadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Field_Password {
            get {
                return ResourceManager.GetString("Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Field_Productos {
            get {
                return ResourceManager.GetString("Field_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgrupo de Cuenta.
        /// </summary>
        public static string Field_SubGrupoCuenta {
            get {
                return ResourceManager.GetString("Field_SubGrupoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgrupos.
        /// </summary>
        public static string Field_Subgrupos {
            get {
                return ResourceManager.GetString("Field_Subgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublíneas.
        /// </summary>
        public static string Field_Sublineas {
            get {
                return ResourceManager.GetString("Field_Sublineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string Field_Username {
            get {
                return ResourceManager.GetString("Field_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID del Grupo.
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo de cuenta es obligatorio.
        /// </summary>
        public static string GrupoCuentaObligatorio {
            get {
                return ResourceManager.GetString("GrupoCuentaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un grupo de cuenta válido.
        /// </summary>
        public static string GrupoCuentaSeleccion {
            get {
                return ResourceManager.GetString("GrupoCuentaSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales inválidas.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la línea debe tener exactamente 2 caracteres.
        /// </summary>
        public static string LineaCodigoLongitud {
            get {
                return ResourceManager.GetString("LineaCodigoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La línea es obligatoria.
        /// </summary>
        public static string LineaObligatoria {
            get {
                return ResourceManager.GetString("LineaObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una línea válida.
        /// </summary>
        public static string LineaSeleccion {
            get {
                return ResourceManager.GetString("LineaSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el inicio de sesión.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma Proporcionado.
        /// </summary>
        public static string ProvidedLanguage {
            get {
                return ResourceManager.GetString("ProvidedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es obligatorio.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es obligatoria.
        /// </summary>
        public static string RequiredFemale {
            get {
                return ResourceManager.GetString("RequiredFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} debe tener entre {2} y {1} caracteres.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no puede exceder {1} caracteres.
        /// </summary>
        public static string StringLengthMax {
            get {
                return ResourceManager.GetString("StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID del Subgrupo.
        /// </summary>
        public static string SubGroupId {
            get {
                return ResourceManager.GetString("SubGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe ser numérico con 5 dígitos (Ejemplo: 01001).
        /// </summary>
        public static string SubGrupoCuentaCodigoFormato {
            get {
                return ResourceManager.GetString("SubGrupoCuentaCodigoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del subgrupo debe tener exactamente 5 caracteres.
        /// </summary>
        public static string SubGrupoCuentaCodigoLongitud {
            get {
                return ResourceManager.GetString("SubGrupoCuentaCodigoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El subgrupo de cuenta es obligatorio.
        /// </summary>
        public static string SubGrupoCuentaObligatorio {
            get {
                return ResourceManager.GetString("SubGrupoCuentaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un subgrupo de cuenta válido.
        /// </summary>
        public static string SubGrupoCuentaSeleccion {
            get {
                return ResourceManager.GetString("SubGrupoCuentaSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe ser numérico con 5 dígitos (Ejemplo: 01100).
        /// </summary>
        public static string SubLineaCodigoFormato {
            get {
                return ResourceManager.GetString("SubLineaCodigoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la sublínea debe tener exactamente 5 caracteres.
        /// </summary>
        public static string SubLineaCodigoLongitud {
            get {
                return ResourceManager.GetString("SubLineaCodigoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas Soportados.
        /// </summary>
        public static string SupportedLanguages {
            get {
                return ResourceManager.GetString("SupportedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traducción actualizada exitosamente.
        /// </summary>
        public static string TranslationUpdated {
            get {
                return ResourceManager.GetString("TranslationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma no soportado. Use uno de los idiomas permitidos.
        /// </summary>
        public static string UnsupportedLanguage {
            get {
                return ResourceManager.GetString("UnsupportedLanguage", resourceCulture);
            }
        }
    }
}
